select * from customers limit 20;

--- 1.what is total revevne generated by male vs female customers ?

select gender ,sum(purchase_amount) as revenue from customers group by gender;

--- 2.which customers used a discount but still more than the averge purchase amount

select customer_id ,purchase_amount
from customers
where discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount) from customers);

---3.which are the top five product with highest review rating

select item_purchased ,avg(review_rating) as "Average product rating" from customers 
group by item_purchased
order by avg(review_rating)desc limit 5;

--or

select item_purchased ,Round(avg(review_rating::numeric),2) as "Average product rating" from customers 
group by item_purchased
order by avg(review_rating)desc limit 5;

--- 4.Compare the avergae purchase amount between standard and express shipping
select shipping_type,
Round(avg(purchase_amount),2)
from customers
where shipping_type in ('Standard','Express')
group by shipping_type;


--- 5.Do subscribe customer spend more ?compare aveerge speed and total revene
--- between subscriber and non-subsribers.

select subscription_status,
count(customer_id) as total_customers,
Round(avg(purchase_amount),2) as avg_spending,
Round(sum(purchase_amount),2) as total_revenue
from customers group by subscription_status
order by total_revenue,avg_spending;


---6. which 5 product have the highest percentage of purchase with discount applied 
select item_purchased ,
Round(100*SUM(CASE WHEN discount_applied='Yes' Then 1 else 0 END)/count(*),2) as discount_rate
from customers group by item_purchased
order by discount_rate desc limit 5;


---7.Segment customersss into new ,retirnung and loyal based on their total
---number of previous purchases and show the count of each segment.

with customer_type as(
select customer_id ,previous_purchases,
CASE WHEN previous_purchases =1 then 'New'
     WHEN previous_purchases Between 2 AND 10 then 'Returning'
	 else 'Loyal'
	 END AS customer_segment
from customers)

select customer_segment,count(*) as "Number of Customers"
from customer_type 
group by customer_segment


--- 8.what are the top3 most purchased products within the each category?

with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() OVER (partition by category order by count(customer_id) desc) as item_rank 
from customers
group by category ,item_purchased 
)

select item_rank,category,item_purchased,total_orders
from item_counts 
where item_rank < 3;


--- 9.Are customes who are repeat buyer (more than 5 previous purchases) also more likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customers where previous_purchases >5
group by subscription_status 


---10. what is the revenue contribution of each age group ?
select age_group,
sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc;